services:
  - type: web
    name: trinetra-drug-monitor
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_NAME
        value: telegram_drug_monitor
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /app
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata/
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    buildCommand: |
      echo "Starting build process..."
      echo "Python version: $(python --version)"
      echo "Tesseract version: $(tesseract --version)"
      echo "Build completed successfully"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - app:app"
    autoDeploy: true
    healthCheckPath: /health
    plan: starter
    disk:
      name: trinetra-disk
      mountPath: /app/temp
      sizeGB: 2
    scaling:
      minInstances: 1
      maxInstances: 5
    region: oregon
